name: Update Sitemap

on:
  schedule:
    - cron: '0 */1 * * *'
  issues:
    types: [pinned]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: junxnone/update-readme@ghmainpage
        with:
          push_branch: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          docs_path: "docs"
