name: Update Sitemap

on:
  schedule:
    - cron: '*/10 * * * *'
  issues:
    types: [pinned]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: junxnone/update-readme@ghmainpage
        with:
          push_branch: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          docs_path: "docs"
