name: Update Sitemap
on:
  issues:
    types: [pinned]
  schedule:
    - cron: '33 00 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: junxnone/update-readme@ghmainpage
        with:
          push_branch: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          docs_path: "docs"
